#!/bin/bash

set -e

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

case "$(uname -s)" in
  Darwin ) SHUF_COMMAND='gshuf' ;;
  * ) SHUF_COMMAND='shuf' ;;
esac

if ! type "$SHUF_COMMAND" > /dev/null 2>&1; then
  echo "'$SHUF_COMMAND' command not found" >&2
  exit 1
fi

MESHI_LIST_PATH="$SCRIPT_DIR/meshi.list"

if [ "$1" != '' ]; then
  echo $1
else
  cat $MESHI_LIST_PATH | $SHUF_COMMAND | head -1
fi
